name: test_soundboard_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.19+19

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  audioplayer: ^0.5.2
  
  volume: ^0.1.0

  path_provider:
  

  shared_preferences:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_admob: ^0.9.0+1
  audioplayers: ^0.13.2




dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/garyVeeTestBG1.png
   - assets/sounds/responses/you_did.mp3
   - assets/sounds/im/business_man.mp3
   - assets/sounds/service-bell_daniel_simion.mp3
   - assets/sounds/im/business_man_real.mp3
   - assets/sounds/responses/welcome.mp3
   - assets/sounds/misc/really_turns_me_on.mp3
   - assets/sounds/sayings/early_bird.mp3
   - assets/sounds/misc/dick_pants_47.mp3
   - assets/sounds/responses/this_is_real_talk.mp3
   - assets/sounds/responses/i_feel_bad.mp3
   - assets/sounds/misc/juice_from_moon.mp3
   - assets/sounds/responses/shit_man.mp3
   - assets/sounds/responses/youre_not_happy.mp3
   - assets/sounds/responses/entrepeneurshiop_is_cool.mp3
   - assets/sounds/misc/piano_on_face.mp3
   - assets/sounds/responses/thats_fucking_amazing.mp3
   - assets/sounds/responses/im_just_so_tired.mp3
   - assets/sounds/responses/thats_exactly_right.mp3
   - assets/sounds/responses/100Percent.mp3 
   - assets/sounds/responses/Listen.mp3
   - assets/sounds/responses/IDontKnow.mp3
   - assets/sounds/responses/YouGuysHere.mp3
   - assets/sounds/responses/Yes.mp3
   - assets/sounds/responses/No.mp3
   - assets/sounds/responses/ItsRealSimple.mp3
   - assets/sounds/responses/HumanBehavior.mp3
   - assets/sounds/misc/ShesAGangster.mp3
   - assets/sounds/misc/HelloHongKong.mp3
   - assets/sounds/responses/YoureNot.mp3
   - assets/sounds/curse/Fucken.mp3
   - assets/sounds/curse/FuckTheMan.mp3
   - assets/sounds/IDontGiveAFuck.mp3
   - assets/sounds/TheFuckYouThink.mp3 
   - assets/sounds/curse/AintShit.mp3
   - assets/sounds/curse/CrazyShit.mp3
   - assets/sounds/curse/FuckedUp.mp3
   - assets/sounds/curse/FuckenSuck.mp3
   - assets/sounds/curse/FuckenTrash.mp3
   - assets/sounds/curse/Shit.mp3
   - assets/sounds/curse/ShitOnYou.mp3 
   - assets/sounds/curse/AintShit.mp3 
   - assets/sounds/curse/FuckedUpReal.mp3
   - assets/sounds/misc/LunchRoomShit.mp3
   - assets/sounds/sayings/early_bird.mp3
   - assets/sounds/sayings/ThisIsFunny.mp3
   - assets/sounds/sayings/HireSomebody.mp3
   - assets/sounds/sayings/Players.mp3
   - assets/sounds/sayings/DoTheirThing.mp3
   - assets/sounds/sayings/UnderstandThat.mp3
   - assets/sounds/sayings/MostImportantWord.mp3
   - assets/sounds/misc/HighOnSupply.mp3
   - assets/sounds/sayings/ThisIsFunnyReal.mp3
   - assets/sounds/sayings/UnderstandThatReal.mp3
   - assets/sounds/sayings/LessMarathons.mp3
   - assets/sounds/sayings/LessFortnite.mp3
   - assets/sounds/sayings/FishingPole.mp3
   - assets/sounds/sayings/YourDream.mp3
   - assets/sounds/sayings/JustGoDo.mp3
   - assets/sounds/sayings/OtherOpinions.mp3
   - assets/sounds/sayings/TryShit.mp3
   - assets/sounds/sayings/TryShit2.mp3
   - assets/sounds/sayings/DecideNo.mp3
   - assets/sounds/sayings/LoveLosing.mp3
   - assets/sounds/misc/Hotdogs.mp3
   - assets/sounds/misc/21Savage.mp3
   - assets/sounds/misc/TheWorld.mp3
   - assets/sounds/misc/Fatpants86.mp3
   - assets/sounds/misc/FoodTaste.mp3
   - assets/sounds/sayings/ParentOpinion.mp3
   - assets/sounds/sayings/Friends.mp3
   - assets/sounds/misc/Blueberries.mp3
   - assets/sounds/misc/Blueberries2.mp3
   - assets/sounds/misc/FuckYouGrandpa.mp3
   - assets/sounds/curse/FuckFaces.mp3
   - assets/sounds/misc/ILoveCurse.mp3
   - assets/sounds/curse/DickFace.mp3
   - assets/sounds/curse/NobodyGivesAFuck.mp3
   - assets/sounds/curse/JackShit.mp3
   - assets/sounds/curse/FuckTheMan.mp3
   - assets/sounds/curse/DoneShit.mp3
   - assets/sounds/curse/YoureLost.mp3
   - assets/sounds/misc/HandEye.mp3
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Comfortaa
       fonts:
        - asset: assets/fonts/Comfortaa-Regular.ttf
        - weight: 400
     - family: Comfortaa Bold
       fonts: 
        - asset: assets/fonts/Comfortaa-Bold.ttf
        - weight: 700
     - family: Comfortaa Light
       fonts: 
        - asset: assets/fonts/Comfortaa-Light.ttf
        - weight: 300
     - family: Permanent Marker
       fonts: 
        - asset: assets/fonts/PermanentMarker-Regular.ttf
        - weight: 400
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
